version: '3'
services:
  db:
    build:
      context: ./MySQL-docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: .
      dockerfile: Go-docker/Dockerfile
    volumes:
      - ".:/go/src/app"
    container_name: golang_app
    ports:
      - "8880:8880"
    tty: true
    depends_on:
      - db
