version: '3'

services:
    server:
        build:
            context: .
            dockerfile: ./docker_files/Dockerfile
        image: go_server
        container_name: go_server
        ports:
            - "8880:8880"
        tty: true
        links:
            - "database"
        depends_on:
            - "database"
        networks:
            - vote_net

    database:
        build:
            context: .
            dockerfile: ./docker_files/Dockerfile-mysql
        image: mysql_db
        container_name: mysql_db
        ports:
            - "3306:3306"
        command: --init-file /data/application/init.sql
        volumes:
            - ./init_db.sql:/data/application/init.sql
#            - ./mysql_data/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: voting
            MYSQL_USER: bob
            MYSQL_PASSWORD: secret
        tty: true
        networks:
            - vote_net
            #ipv4_address: 172.60.0.21

              #webserver:
              #    image: nginx:mainline-alpine
              #    container_name: webserver
              #    hostname: webserver
              #    ports:
              #        - "80:80"
              #        - "443:443"
              #    volumes:
              #        - ./nginx-conf:/etc/nginx/conf.d
              #          #- ./cert.pem:/etc/ssl/private/fullchain.pem
              #          #- ./key.pem:/etc/ssl/private/privkey.pem
              #    depends_on:
              #        - server
              #        - database
              #    networks:
              #        - backend
#             #     network_mode: "host"

networks:
    vote_net:
        external: true
