version: '3'

services:
    server:
        build:
            context: .
            dockerfile: ./docker_files/Dockerfile
        image: go_server
        container_name: go_server
        ports:
            - "8880:8880"
        tty: true
        volumes:
            - ./:/go/src/app/
        command: ["go", "run", "cmd/data-access-api/main.go"]
        links:
            - "database"
        depends_on:
            - "database"
        networks:
            - vote_net

    database:
        image: mysql:latest
        container_name: mysql_db
        #ports:
        #    - "3306:3306"
              #command: --init-file /data/application/init.sql
              #command: sh -c "python3 /home/populate_db.py"
        volumes:
            - ./init_db.sql:/data/application/init.sql
            - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
#            - ./mysql_data/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: VV@WF9Xf8C6!#Xy!
            MYSQL_DATABASE: voting
        tty: true
        networks:
            - vote_net

    webserver:
      image: nginx:mainline-alpine
      container_name: webserver
      hostname: webserver
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./nginx-conf:/etc/nginx/conf.d
            #- ./cert.pem:/etc/ssl/private/fullchain.pem
            #- ./key.pem:/etc/ssl/private/privkey.pem
      links:
          - "server"
      depends_on:
          - "server"
          - "database"
      networks:
          - vote_net

networks:
    vote_net:
        external: true
