FROM mysql:latest

# Do something
#RUN apt-get update && apt-get install -y \
#    python3 \
#    python3-pip

#RUN pip3 install pandas mysql-connector-python

#WORKDIR /home/app

#COPY *.py .
#COPY data/ ./data/

#RUN python3 populate_db.py
